name: Deploy project1 to EC2

on:
  push:
    branches:
      - main   # <--- CHECK THIS: Change to 'main' if that is your default branch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Login to GitHub Container Registry (using the temporary action token)
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # 2. Pull the new image
            docker pull ghcr.io/${{ env.IMAGE_NAME }}:latest
            
            # 3. Create network if it doesn't exist (Safety check)
            docker network create app-network || true
            
            # 4. Stop and remove the old container
            docker stop project1 || true
            docker rm project1 || true
            
            # 5. Run the new container
            docker run -d \
              --name project1 \
              --restart unless-stopped \
              --network app-network \
              ghcr.io/${{ env.IMAGE_NAME }}:latest
